pool:
  vmImage: 'windows-latest'

variables:
  solution: 'src/Nullable.Extended.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: PowerShell@1
  displayName: 'Set build version'
  inputs:
    scriptType: inlineScript
    inlineScript: |
     (new-object Net.WebClient).DownloadString("https://raw.github.com/tom-englert/BuildScripts/master/BuildScripts.ps1") | iex
     Project-SetVersion "src\Directory.Build.props" | Build-AppendVersionToBuildNumber
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

- task: VSBuild@1
  displayName: Build
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '-restore'
  env:
    DeployExtension: False  

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: '$(solution)'
    arguments: '--no-build --configuration $(buildConfiguration)'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'src'
    Contents: '**\$(buildConfiguration)\*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\Nuget'
    flattenFolders: true

- task: CopyFiles@2
  inputs:
    SourceFolder: 'src'
    Contents: '**\$(buildConfiguration)\**\*.vsix'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\Vsix'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\Nuget'
    ArtifactName: 'Package'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\Vsix'
    ArtifactName: 'Vsix'
    publishLocation: 'Container'

- task: PowerShell@1
  displayName: 'Publish to vsix-gallery'
  enabled: 'true'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    scriptType: inlineScript
    inlineScript: |
      (new-object Net.WebClient).DownloadString("https://raw.github.com/tom-englert/BuildScripts/master/BuildScripts.ps1") | iex
      Vsix-PublishToGallery "$(Build.ArtifactStagingDirectory)\Vsix\Nullable.Extended.Extension.vsix"

